### ISSUE TITLE
Android Studio 1.1 exception while translating anything

### ISSUE THREAD

**Issue by xklakoux** [westlinkin/AndroidLocalizationer#15]
I'm using Android Studio 1.1.0
Build #AI-135.1740770, built on February 18, 2015 on OSX

When I try to translated anything I get following error.

```
Index: 49, Size: 49: Index: 49, Size: 49
java.lang.IndexOutOfBoundsException: Index: 49, Size: 49
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at data.task.GetTranslationTask.getTranslationEngineResult(GetTranslationTask.java:171)
	at data.task.GetTranslationTask.run(GetTranslationTask.java:96)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

Thanks for taking a look!

**Comment by westlinkin** [comment]
Can you provide your `strings.xml` file?

**Comment by xklakoux** [comment]
Sure. Here you go http://hastebin.com/fayicicoxo.xml

**Comment by westlinkin** [comment]
There is nothing in the link you gave me.

**Comment by xklakoux** [comment]
Sorry. Try this http://pastebin.com/n7P70ZdQ

**Comment by westlinkin** [comment]
Got it, will fix it within 24-36 hours.
