### ISSUE TITLE
NullPointerException  : GetTranslationTask.getTranslationEngineResult(GetTranslationTask.java:142)

### ISSUE THREAD

**Issue by shiguang1120** [westlinkin/AndroidLocalizationer#35]
Android Studio 2.2.20

Plugin Error
Android Localizationer threw an uncaught NullPointerException. Disable Plugin

null
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at language_engine.bing.BingTranslationApi.getAccessToken(BingTranslationApi.java:64)
	at data.task.GetTranslationTask.getTranslationEngineResult(GetTranslationTask.java:142)
	at data.task.GetTranslationTask.run(GetTranslationTask.java:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RogueJun** [comment]
同上

**Comment by qtchenxz** [comment]
同上

**Comment by maowentao0416** [comment]
me too

**Comment by Virgilseed** [comment]
me too

**Comment by Virgilseed** [comment]
android studio 3.0Beta 2

**Comment by Fish-Bin** [comment]
@shiguang1120 问题解决没？

**Comment by megvil** [comment]
I fixed it ，before use it，you must get the google transltation Api key ,set in the AS 。for more info. open this :https://cloud.google.com/translate/docs/getting-started?csw=1 @rainbowBin @Virgilseed @maowentao0416 @shiguang1120
